/*
 * Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:
 * 
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
 */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <limits.h>

#define P(n) ((n) * (3 * (n) - 1) / 2)
#define LIMIT 10000

int main(int argc, const char *argv[])
{
  int j, pj, k, pk;
  int result = INT_MAX, sum, diff;
  int *ipentagonals = calloc(P(LIMIT), sizeof(int));
  int *pentagonals = malloc(sizeof(int) * LIMIT);
  int i, tmp;
  for (i = 0; i < LIMIT; i++) {
    tmp = P(i + 1);
    ipentagonals[tmp] = i + 1;
    pentagonals[i] = tmp;
  }

  for (j = 0; j < LIMIT; j++) {
    for (k = 0; k < LIMIT; k++) {
      if (j == k) {
        break;
      }
      sum = pentagonals[j] + pentagonals[k];
      if (sum < pentagonals[LIMIT - 1] && ipentagonals[sum]) {
        diff = (int)abs(pentagonals[k] - pentagonals[j]);
        if(ipentagonals[diff]) {
          printf("j = %d, k = %d, pj = %d, pk = %d\n", j, k, pentagonals[j], pentagonals[k]);
          printf("Sum = %d, which is the %d pentagonal number\n", sum, ipentagonals[sum]);
          printf("Diff = %d, which is the %d pentagonal number\n", diff, ipentagonals[diff]);
          if(result > diff) {
            result = diff;
          }
        }
      }
    }
  }

  printf("Result: %d\n", result);

  return 0;
}
